learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Main page
    path('', views.index, name='index'),
    # Topics page
    path('topics', views.topics, name='topics'),
    # Page for a specific topic
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # Add a new topic
    path('create_topic', views.new_topic, name="new_topic"),
    # Add a new entry for specific topic
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Edit entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    # Add a new comment for the specific entry
    path('create_comment', views.new_comment, name="new_comment"),
    
    path('get_comments/<int:entry_id>/', views.get_comments, name='get_comments'),
    
    
]

users/urls.py
"""Define regular statments URL"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    is_private = models.BooleanField(default=False)
    
    def __str__(self):
        return self.text
    

class Entry(models.Model):
    
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    date_added = models.DateTimeField(auto_now=True)
    
    class Meta:
        verbose_name_plural = 'entries'
        
    def __str__(self):
        return f"{self.text[:50]}..."
    

class Comment(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry, Comment


class TopicForm(forms.ModelForm):
     class Meta:
         model = Topic
         fields = ['text', 'is_private']
         labels = {'text': ''}
         
         
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.template.loader import render_to_string

from .models import Topic, Entry, Comment
from .forms import TopicForm, EntryForm, CommentForm

# Create your views here.
def index(request):
    """General page"""
    return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(is_private=False).order_by('date_added')
    my_topics = Topic.objects.filter(owner=request.user, is_private=True).order_by('date_added')
    context = {'topics': topics, 'my_topics': my_topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    
    if (topic.is_private == True):
        check_topic_owner(request, topic)
    
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(request, topic)
    
    if request.method != 'POST':
        form = EntryForm
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
        
    context = {"topic": topic, "form": form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(request, topic)
    
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def new_comment(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    _check_entry(request, entry, topic)
    
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.entry = entry
            new_comment.save()
            return redirect('learning_logs:public_entry', entry_id = entry_id)
    context = {"entry": entry, "form": form}
    return render(request, 'learning_logs/new_comment.html', context)

@login_required
def topics(request):
    topics = Topic.objects.filter(is_private=False).order_by('date_added')
    my_topics = Topic.objects.filter(owner=request.user, is_private=True).order_by('date_added')
    context = {'topics': topics, 'my_topics': my_topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def entry_comments(request):
    comments = Comment.objects.order_by('date_added')
    context = {'comments': comments}
    return render

@login_required
def get_comments(request):
    entry_id = request.GET.get('entry_id')
    entry = Entry.objects.get(pk=entry_id)
    comments = Comment.objects.filter(entry=entry)
    comments_html = render_to_string('comments.html', {'comments': comments})

    return JsonResponse({'comments': comments_html})
    
    

def check_topic_owner(request, topic):
    if topic.owner != request.user:
        raise Http404
    
def _check_entry(request, entry, topic):
    if (entry.owner != request.user) and (topic.is_private == True):
        raise Http404
            

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
        
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
    
<head>
    <meta charset="utf-8">
    <meta name='viewport' contert="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block javascript %}{% endblock javascript %}
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>    

        <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'learning_logs:topics'%}">Topics</a></li>
              </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text"}>Hello, {{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

    
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>
        <a href="{%  url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>

    <p>Edit entry:</a>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <div class="jumbotron"  style="background: linear-gradient(to bottom, #ff3399, #9900cc);">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">Make your own Learning Log, and keep a list of the topics
        you're learning about. Whenever you learn something new about a topic,
        make an entry summarizing what you've learned.</p>

    {% if user.is_authenticated %}
    <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}"
        role="button">Begin &raquo;</a>
    {% else %}
    <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
        role="button">Register &raquo;</a>
    {% endif %}
  </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_comment.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>
        <a href="{%  url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>

    <p>Add a new comment:</a>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add comment</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>
        <a href="{%  url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </p>

    <p>Add a new entry:</a>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/public_entry.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new comment</a>
  </p>

{% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
        edit entry</a></small>
    </h4>
    <div class="card-body">
      {{ entry.text|linebreaks }}
    </div>   
  </div>  
{% empty %}
  <p>There are no entries for this topic yet.</p>
{% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

{% for entry in entries %}
  <div class="card mb-3">
    <h4 class="card-header">
      {{ entry.date_added|date:'M d, Y H:i' }}
      <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
        edit entry</a></small>
    </h4>
    <div class="card-body">
      {{ entry.text|linebreaks }}
    </div>
    
    <div class="card-footer">
      <button class="show-comments-btn" data-entry-id="{{ entry.id }}">Comments</button>
    </div>
    <div class="comments-container">
      <ul>
        {% for comment in entry.comment_set.all %}
          <li>{{ comment.text }}</li>
        {% endfor %}
      </ul>
    </div>
  </div>  
{% empty %}
  <p>There are no entries for this topic yet.</p>
{% endfor %}
.comments-container {
  display: none;
}

.comments-visible .comments-container {
  display: block;
}


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
      $('.show-comments-btn').on('click', function() {
        var commentsContainer = $(this).closest('.card').find('.comments-container');
        commentsContainer.toggleClass('comments-visible');
      });
    });
  </script>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
  <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
<ul>
  {% for topic in topics %}
    <li><h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
  {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
  {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new public topic</a></h3>

<h1 style="margin-top:30px;">My private records</h1>
<ul>
  {% for topic in my_topics %}
    <li><h3>
      <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
    </h3></li>
  {% empty %}
    <li><h3>No topics have been added yet.</h3></li>
  {% endfor %}

</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new private record</a></h3>


{% endblock content %}